export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const IS_FETCHING = 'IS_FETCHING';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const SUBMIT_EXPENSE_EDITED = 'SUBMIT_EXPENSE_EDITED';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
